spring:
  application:
    name: "Hotel Reservation API"
  config:
    import: optional:dotenv:.env
  profiles:
    active: dev

# Security Configuration
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION_TIME}